### PR TITLE
Improved types for useDeskproLatestAppContext

### PR DESCRIPTION
**Pull request by zpawn**
Converted simple type to generic for pass Data and Settings in the useDeskproLatestAppContext hook.

### CODE REVIEW

**Review by HappyPaul55 — CHANGES_REQUESTED** [review]
I'd expect `data` and `settings` to be given a type that isn't any. This just looks like we're passing `any` around which isn't much of an improvement.

**Comment by zpawn** [comment]
> I'd expect `data` and `settings` to be given a type that isn't any. This just looks like we're passing `any` around which isn't much of an improvement.

I left `DeskproAppContextValue<Data = any, Settings = any>` in one place because it breaks the typing, and digging into the `app-sdk` typing would take too long. But this type improvement fixes about 30 eslint errors in HubSpot App

**Review by AshleyDawson — COMMENTED** [review]
Spoke to Ilia and he states:

> I left DeskproAppContextValue<Data = any, Settings = any> in one place because it breaks the typing, and digging into the app-sdk typing would take too long. But this type improvement fixes about 30 eslint errors in HubSpot App

merging to unblock Ilia, if there's an issue please contact @AshleyDawson

**Review by AshleyDawson — APPROVED** [review]

**Comment by AshleyDawson** [comment]
@zpawn has stated:

> I left DeskproAppContextValue<Data = any, Settings = any> in one place because it breaks the typing, and digging into the app-sdk typing would take too long. But this type improvement fixes about 30 eslint errors in HubSpot App (e

Force merging to unblock Ilia, but all comments need to be addressed or discussed in a later PR

**Pull request merged**
